// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-J2OdSIOBZLYiA-JavO5eaAVdqFHJgOQ',
    appId: '1:929837617513:web:333179ea490322ae88adf8',
    messagingSenderId: '929837617513',
    projectId: 'fyp-project-db-final',
    authDomain: 'fyp-project-db-final.firebaseapp.com',
    storageBucket: 'fyp-project-db-final.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD537Mys2sN0aF9SIPfve0GlrDZtpP9xPk',
    appId: '1:929837617513:android:0df322471ee0524488adf8',
    messagingSenderId: '929837617513',
    projectId: 'fyp-project-db-final',
    storageBucket: 'fyp-project-db-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTY-JURz9dPv9_P3PWsNcj_s2HOjdRCgE',
    appId: '1:929837617513:ios:bd7f15f892e29e1b88adf8',
    messagingSenderId: '929837617513',
    projectId: 'fyp-project-db-final',
    storageBucket: 'fyp-project-db-final.appspot.com',
    iosBundleId: 'com.example.fypApp',
  );
}
